import Head from "next/head";
import Link from "next/link";
import Layout from "~/components/Layout";
import { signIn, signOut, useSession } from "next-auth/react";

export default function Home() {
  const session = useSession();
  console.log("session -> ", session);

  if (!session.data) {
    return (
      <div className="grid h-screen">
        <div className="flex flex-col items-center gap-16 place-self-center">
          <div>
            {/* <Image
              src="/assets/logo-main.webp"
              alt="logo"
              width={192}
              height={192}
              priority
            /> */}
          </div>
          <div className="flex flex-col items-center gap-6">
            <span>You must be signed in to use this application!</span>
            <button onClick={() => signIn()}>Sign in</button>
          </div>
        </div>
      </div>
    );
  }

  return (
    // <>
    //   <Head>
    //     <title>Create T3 App</title>
    //     <meta name="description" content="Generated by create-t3-app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>
    //   <Layout>
    //     {/* <Link href="/signup">Sign Up</Link> */}
    //     {/* <Link href="/signin">Sign In</Link> */}
    //     <button onClick={() => signIn()}>sign in</button>
    //   </Layout>
    // </>
    <>
      <h1>there is a session</h1>
      <button onClick={() => signOut()}>sign out</button>
    </>
  );
}
